---
title: "Linear Regression Mini-competition"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
data<-read.csv("~/Desktop/CIS635W23/STA 631 W24/teamproject1/competition-files/news.csv")
library(tidyverse)
library(lubridate)
library(tidymodels)
tidymodels_prefer()
library(ggplot2)
library(ggcorrplot)
 #Your tasks is to create a linear model that best predicts the sentiment of the sentiment score for a news items’ headline.
options(scipen=999)
```

```{r, data cleanup}

#removing significant missing values for Headline, Source and Facebook/GooglePlus/LinkedIn
  #filter(Title==""|is.na(Title))#0
  #filter(Headline==""|is.na(Headline)) #15
  #filter(Topic==""|is.na(Topic)) #0
  #filter(Source==""|is.na(Source)) #273
  #filter(Facebook<0|GooglePlus<0,LinkedIn<0) #5000

#clean up data
df<-data|>
  #pull date from publishing timestamp
  mutate(date=as.Date(sub(" .*", "", PublishDate),"%m/%d/%Y"),
         #create a weekday variable in case day of the week article was published contributes to sentiment
         DoW=wday(date, abbr = FALSE),
         #track word counts in title and headline in case they contribute to sentiment
         titleWC=str_count(Title, '\\w+'),
         headlineWC=str_count(Headline, '\\w+'))|>
  #filter to remove missing values found above
  filter(Facebook>=0,
         GooglePlus>=0,
         LinkedIn>=0,
         Headline!="",
         !is.na(Headline),
         Source!="",
         Source!=" ")
#There are so many unique sources, we want to get a count of publishing frequency to see if this allows us to remove sources from the model
counts<-df|>
  count(Source)

#join counts back to original df
df<-left_join(df,counts,by="Source")

#sort the counts for source into bins based on publishing frequency
df<-df%>%
  mutate(
    sourcegroup=as.factor(case_when(
    n<=302~"low_publish_rate",
    n>=303&n<=603~"med_low_publish_rate",
    n>=604&n<=904~"med_publish_rate",
    n>=905&n<=1205~"med_high_publish_rate",
    n>=1206~"high_publish_rate")),
    #extract month/year from date
    month=as.factor(format(as.Date(date), "%Y-%m")),
    #set other variables to factors
    Topic=as.factor(Topic),
    DoW=as.factor(DoW))%>%
  select(-c(IDLink,Title,Headline,PublishDate,Source,date,n))


#see a summary of the df data
summary(df)
#look at a correlation plot of all variables (one-hot encoded to allow to correlation between categorical variables)
#model.matrix(~0+., data=df)%>% 
#  cor(use="pairwise.complete.obs") %>% 
#  ggcorrplot(show.diag=FALSE, method="square",type="upper", lab=TRUE, lab_size=2)

```

```{r, first title model}
set.seed(456)

#remove sentiment headline from the model
sentimentTitle<-df%>%
  select(-SentimentHeadline)

#build a recipe using the all variables as predictors
titlerecipe <- recipe(
  #set your formula 
  SentimentTitle ~ .,
  data = sentimentTitle) 
#create a flow that one-hot encodes
titleflow<-titlerecipe %>%
  step_dummy(all_nominal_predictors(),one_hot=TRUE) %>% #one-hot encode
  prep()
#bake the recipe into dataset 
test<-bake(titleflow,new_data = NULL)


#using rsample package, split data with 25% to test and 75% to training
split_Title <- initial_split(test,prop = 3/4)
#set your training data based on split parameters
train_title <- training(split_Title)
#set your testing data based on split parameters
test_title <- testing(split_Title)


#set model, set engine
linear_mod_title <- linear_reg() %>%
      set_engine("lm")

#fit model with prepped data from recipe
linear_title <- fit(formula = SentimentTitle ~., linear_mod_title, data = train_title)
#predict on test data already prepped from recipe
lm_predicted_title <- predict(linear_title, new_data = test_title)

#get predictions and actual values
lm_title_evaluation <- as.data.frame(cbind(lm_predicted_title, test_title$SentimentTitle))
colnames(lm_title_evaluation) <- c("Predicted", "Actual")

#evaluation metrics
rmse(lm_title_evaluation, truth = Actual, estimate = Predicted)
rsq(lm_title_evaluation, truth = Actual, estimate = Predicted)
mae(lm_title_evaluation, truth = Actual, estimate = Predicted)



tidy(linear_title)

ggplot(lm_title_evaluation, aes(x = Predicted, y = Actual, color=Predicted)) + 
                 geom_point(alpha=0.3) + 
                 geom_abline(lty = 2, color = "gray80", size = 1.5)+
                 labs(color=NULL,
                      title = "Predicted and True Title Sentiment")


```

```{r, title model 2}
test<-test%>%
  select(GooglePlus,titleWC,SentimentTitle,Topic_economy,Topic_microsoft,Topic_obama,Topic_palestine,DoW_X4,month_X2015.11)

split_Title <- initial_split(test,prop = 3/4)
#set your training data based on split parameters
train_title <- training(split_Title)
#set your testing data based on split parameters
test_title <- testing(split_Title)


#set model, set engine
linear_mod_title <- linear_reg() %>%
      set_engine("lm")

#fit model with prepped data from recipe
linear_title <- fit(formula = SentimentTitle ~., linear_mod_title, data = train_title)
#predict on test data already prepped from recipe
lm_predicted_title <- predict(linear_title, new_data = test_title)

#get predictions and actual values
lm_title_evaluation <- as.data.frame(cbind(lm_predicted_title, test_title$SentimentTitle))
colnames(lm_title_evaluation) <- c("Prediction", "Actual")

#evaluation metrics
rmse(lm_title_evaluation, truth = Actual, estimate = Prediction)
rsq(lm_title_evaluation, truth = Actual, estimate = Prediction)
mae(lm_title_evaluation, truth = Actual, estimate = Prediction)


tidy(linear_title)


ggplot(lm_title_evaluation, aes(x = Prediction, y = Actual, color=Prediction)) + 
                 geom_point(alpha=0.3) + 
                 geom_abline(lty = 2, color = "gray80", size = 1.5)+
                 labs(color=NULL,
                      title = "Predicted and True Title Sentiment")


```

```{r, first headline model}

sentimentHL<-df%>%
  select(-SentimentTitle)
#build a recipe 
HLrecipe <- recipe(
  #set your formula 
  SentimentHeadline ~ .,
  data = sentimentHL) 
#create a flow that one-hot encodes
HLflow<-HLrecipe %>%
  step_dummy(all_nominal_predictors(),one_hot=TRUE) %>% #one-hot encode
  prep()
#bake the recipe into dataset 
test<-bake(HLflow,new_data = NULL)


#using rsample package, split data with 25% to test and 75% to training
split_HL <- initial_split(test,prop = 3/4)
#set your training data based on split parameters
train_HL<- training(split_HL)
#set your testing data based on split parameters
test_HL<- testing(split_HL)


#set model, set engine
linear_mod_HL <- linear_reg() %>%
      set_engine("lm")

#fit model with prepped data from recipe
linear_HL<- fit(formula = SentimentHeadline ~., linear_mod_HL, data = train_HL)
#predict on test data already prepped from recipe
lm_predicted_HL <- predict(linear_HL, new_data = test_HL)

#get predictions and actual values
lm_HL_evaluation <- as.data.frame(cbind(lm_predicted_HL, test_HL$SentimentHeadline))
colnames(lm_HL_evaluation) <- c("Prediction", "Actual")

#evaluation metrics
rmse(lm_HL_evaluation, truth = Actual, estimate = Prediction)
rsq(lm_HL_evaluation, truth = Actual, estimate = Prediction)
mae(lm_HL_evaluation, truth = Actual, estimate = Prediction)



tidy(linear_HL)

ggplot(lm_HL_evaluation, aes(x = Prediction, y = Actual, color=Prediction)) + 
                 geom_point(alpha=0.3) + 
                 geom_abline(lty = 2, color = "gray80", size = 1.5)+
                 labs(color=NULL,
                      title = "Predicted and True Title Sentiment")

```

```{r, HEadline model 2}
test_HL<-test_HL%>%
  select(titleWC,SentimentHeadline,Topic_economy,Topic_microsoft,Topic_obama,Topic_palestine,month_X2015.11,month_X2015.12,month_X2016.01,month_X2016.02,month_X2016.03,month_X2016.04,month_X2016.05,month_X2016.06,month_X2016.07)

split_HL <- initial_split(test_HL,prop = 3/4)
#set your training data based on split parameters
train_HL <- training(split_HL)
#set your testing data based on split parameters
test_HL <- testing(split_HL)


#set model, set engine
linear_mod_HL <- linear_reg() %>%
      set_engine("lm")

#fit model with prepped data from recipe
linear_HL <- fit(formula = SentimentHeadline ~., linear_mod_HL, data = train_HL)
#predict on test data already prepped from recipe
lm_predicted_HL <- predict(linear_HL, new_data = test_HL)

#get predictions and actual values
lm_HL_evaluation <- as.data.frame(cbind(lm_predicted_HL, test_HL$SentimentHeadline))
colnames(lm_HL_evaluation) <- c("Prediction", "Actual")

#evaluation metrics
rmse(lm_HL_evaluation, truth = Actual, estimate = Prediction)
rsq(lm_HL_evaluation, truth = Actual, estimate = Prediction)
mae(lm_HL_evaluation, truth = Actual, estimate = Prediction)



tidy(linear_HL)


ggplot(lm_HL_evaluation, aes(x = Prediction, y = Actual, color=Prediction)) + 
                 geom_point(alpha=0.3) + 
                 geom_abline(lty = 2, color = "gray80", size = 1.5)+
                 labs(color=NULL,
                      title = "Predicted and True HL Sentiment")

```

```{r, title with headline sentiment}

#build a recipe using the all variables as predictors
titlerecipe <- recipe(
  #set your formula 
  SentimentTitle ~ .,
  data = df) 
#create a flow that one-hot encodes
titleflow<-titlerecipe %>%
  step_dummy(all_nominal_predictors(),one_hot=TRUE) %>% #one-hot encode
  prep()
#bake the recipe into dataset 
test<-bake(titleflow,new_data = NULL)


#using rsample package, split data with 25% to test and 75% to training
split_Title <- initial_split(test,prop = 3/4)
#set your training data based on split parameters
train_title <- training(split_Title)
#set your testing data based on split parameters
test_title <- testing(split_Title)


#set model, set engine
linear_mod_title <- linear_reg() %>%
      set_engine("lm")

#fit model with prepped data from recipe
linear_title <- fit(formula = SentimentTitle ~., linear_mod_title, data = train_title)
#predict on test data already prepped from recipe
lm_predicted_title <- predict(linear_title, new_data = test_title)

#get predictions and actual values
lm_title_evaluation <- as.data.frame(cbind(lm_predicted_title, test_title$SentimentTitle))
colnames(lm_title_evaluation) <- c("Predicted", "Actual")

#evaluation metrics
rmse(lm_title_evaluation, truth = Actual, estimate = Predicted)
rsq(lm_title_evaluation, truth = Actual, estimate = Predicted)
mae(lm_title_evaluation, truth = Actual, estimate = Predicted)



tidy(linear_title)

ggplot(lm_title_evaluation, aes(x = Predicted, y = Actual, color=Predicted)) + 
                 geom_point(alpha=0.3) + 
                 geom_abline(lty = 2, color = "gray80", size = 1.5)+
                 labs(color=NULL,
                      title = "Predicted and True Title Sentiment")


```

```{r,headline with title sentiment}
#build a recipe 
HLrecipe <- recipe(
  #set your formula 
  SentimentHeadline ~ .,
  data = df) 
#create a flow that one-hot encodes
HLflow<-HLrecipe %>%
  step_dummy(all_nominal_predictors(),one_hot=TRUE) %>% #one-hot encode
  prep()
#bake the recipe into dataset 
test<-bake(HLflow,new_data = NULL)


#using rsample package, split data with 25% to test and 75% to training
split_HL <- initial_split(test,prop = 3/4)
#set your training data based on split parameters
train_HL<- training(split_HL)
#set your testing data based on split parameters
test_HL<- testing(split_HL)


#set model, set engine
linear_mod_HL <- linear_reg() %>%
      set_engine("lm")

#fit model with prepped data from recipe
linear_HL<- fit(formula = SentimentHeadline ~., linear_mod_HL, data = train_HL)
#predict on test data already prepped from recipe
lm_predicted_HL <- predict(linear_HL, new_data = test_HL)

#get predictions and actual values
lm_HL_evaluation <- as.data.frame(cbind(lm_predicted_HL, test_HL$SentimentHeadline))
colnames(lm_HL_evaluation) <- c("Prediction", "Actual")

#evaluation metrics
rmse(lm_HL_evaluation, truth = Actual, estimate = Prediction)
rsq(lm_HL_evaluation, truth = Actual, estimate = Prediction)
mae(lm_HL_evaluation, truth = Actual, estimate = Prediction)



tidy(linear_HL)

ggplot(lm_HL_evaluation, aes(x = Prediction, y = Actual, color=Prediction)) + 
                 geom_point(alpha=0.3) + 
                 geom_abline(lty = 2, color = "gray80", size = 1.5)+
                 labs(color=NULL,
                      title = "Predicted and True Title Sentiment")

```

